### ISSUE TITLE
Using Kafka Broker as Sink in source

### ISSUE THREAD

**Issue by jensg-st** [knative-sandbox/eventing-kafka-broker#1358]
**Describe the bug**

I'm new to knative eventing so it might be just a matter of not understanding the documentation but I want to create a Kafka broker and a Kafka source which sends the event to the broker.

*Broker Config*

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: knative-eventing
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "1"
  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9092"
```

*Creating the broker with the configuration*

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    # case-sensitive
    eventing.knative.dev/broker.class: Kafka
  name: default
  namespace: default
spec:
  # Configuration specific to this broker.
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
```
With these settings the broker is online:

```console
kubectl get broker

NAME      URL                                                                              AGE   READY   REASON
default   http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/default   45m   True    
```

I have tried two KafkaSources. The first one sending to a service is getting created:

```yaml
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source2
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - knative-topic
  sink:
    ref:
      apiVersion: v1
      kind: Service
      namespace: default
      name: my-service
```

With the second one I tried to use the broker as a sink like this:

```yaml
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source3
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - knative-topic
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
```

This source fails with the following error(s):

```console
Status:
  Conditions:
    Last Transition Time:  2021-10-22T00:11:43Z
    Status:                Unknown
    Type:                  ConnectionEstablished
    Last Transition Time:  2021-10-22T00:11:43Z
    Status:                Unknown
    Type:                  Deployed
    Last Transition Time:  2021-10-22T00:11:43Z
    Status:                Unknown
    Type:                  InitialOffsetsCommitted
    Last Transition Time:  2021-10-22T00:11:43Z
    Reason:                NotFound
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-10-22T00:11:43Z
    Reason:                NotFound
    Status:                False
    Type:                  SinkProvided
  Observed Generation:     1
Events:
  Type     Reason           Age                 From                    Message
  ----     ------           ----                ----                    -------
  Normal   FinalizerUpdate  11m                 kafkasource-controller  Updated "kafka-source3" finalizers
  Warning  InternalError    15s (x18 over 11m)  kafkasource-controller  getting sink URI: brokers.eventing.knative.dev "Lister" not found
```

 **Knative release version**

0.26.1 knative eventing
0.26.0 kafka eventing controller
