### ISSUE TITLE
Incorrect image

### ISSUE THREAD

**Issue by mingyang91** [knative-sandbox/eventing-kafka-broker#1806]
**Describe the bug**
The image of `kafka-broker-dispatcher` deployment file of Release v1.1.0 is incorrect. 

 **Knative release version**
v1.1.0

 **Additional context**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-dispatcher
  namespace: knative-eventing
  labels:
    app: kafka-broker-dispatcher
    kafka.eventing.knative.dev/release: "devel"
spec:
  selector:
    matchLabels:
      app: kafka-broker-dispatcher
  template:
    metadata:
      name: kafka-broker-dispatcher
      labels:
        app: kafka-broker-dispatcher
        kafka.eventing.knative.dev/release: "devel"
    spec:
      serviceAccountName: knative-kafka-broker-data-plane
      securityContext:
        runAsNonRoot: true
      containers:
        - name: kafka-broker-dispatcher
          image: gcr.io/knative-releases/knative-kafka-broker-receiver@sha256:b56e81f26185ad916f4a78d165abd60719d15cc88ce8d102a32bad20322a8942 // <- This is typo?
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/config
              name: config-kafka-broker-data-plane
              readOnly: true
            - mountPath: /etc/brokers-triggers
              name: kafka-broker-brokers-triggers
              readOnly: true
            - mountPath: /tmp
              name: cache
            - mountPath: /etc/logging
              name: kafka-broker-config-logging
              readOnly: true
            - mountPath: /etc/tracing
              name: config-tracing
              readOnly: true
```
