### ISSUE TITLE
 eventing-kafka-broker v1.2.1 conflicts and breaks eventing-kafka/pkg/channel/distributed v1.2.0

### ISSUE THREAD

**Issue by matthewchngshopback** [knative-sandbox/eventing-kafka-broker#1893]
**Describe the bug**
Installing `eventing-kafka-broker` alongside `eventing-kafka/channels/distributed` should not prevent `eventing-kafka/channels/distributed` MTChannelBasedBroker's new triggers from becoming `Ready`.

 **Expected behavior**
- Installation of eventing-kafka-broker to the `knative-eventing` namespace should not affect existing eventing kafka/channels/distributed installation
- New triggers created for existing MTChannelBroker (Kafka channel/distributed) should resolve to `Ready` and function as expected.

 **To Reproduce**
Steps to reproduce the behavior.
1. Set up an existing local Kind install with kn-quickstart v1.2
2. Install `eventing-kafka/pkg/channel/distrubted` v1.2.0 with the following
  ```
  https://github.com/knative-sandbox/eventing-kafka/releases/download/knative-v1.2.0/source.yaml
  https://github.com/knative-sandbox/eventing-kafka/releases/download/knative-v1.2.0/channel-distributed.yaml
  ```
3. Create new MTChannelBasedBroker backed by Kafka Channels/Distributed.
4. Create new trigger on MTChannelBasedBroker and they resolve to `Ready` immediately and is forwarding events as expected.
5. Apply the following from `eventing-kafka-broker` v1.2 (attempting to install KafkaBroker)
  ```
  https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.1/eventing-kafka-controller.yaml
  ```
6. Existing triggers created in (4) still resolves as `Ready` and continue to function properly at this point.
7. Now, recreating the same trigger as (4) or just new ones for the same broker created in (3) results in the triggers being stuck with the following failing conditions.
  ```
  conditions:
  - lastTransitionTime: "2022-02-11T04:30:20Z"
    status: "True"
    type: BrokerReady
  - lastTransitionTime: "2022-02-11T04:30:20Z"
    message: No dead letter sink is configured.
    reason: DeadLetterSinkNotConfigured
    status: "True"
    type: DeadLetterSinkResolved
  - lastTransitionTime: "2022-02-11T04:30:20Z"
    status: "True"
    type: DependencyReady
  - lastTransitionTime: "2022-02-11T04:30:20Z"
    message: 'Failed to get subscription status: subscription "mtchannelbased-kafka-broker-exa2a1f040e5a7825f9afeb2c358a3c698d"
      not present in channel "mtchannelbased-kafka-broker-kne-trigger" subscriber''s
      list'
    reason: SubscriptionNotMarkedReadyByChannel
    status: Unknown
    type: Ready
  - lastTransitionTime: "2022-02-11T04:30:20Z"
    status: "True"
    type: SubscriberResolved
  - lastTransitionTime: "2022-02-11T04:30:20Z"
    message: 'Failed to get subscription status: subscription "mtchannelbased-kafka-broker-exa2a1f040e5a7825f9afeb2c358a3c698d"
      not present in channel "mtchannelbased-kafka-broker-kne-trigger" subscriber''s
      list'
    reason: SubscriptionNotMarkedReadyByChannel
    status: Unknown
    type: SubscriptionReady
  observedGeneration: 1
  subscriberUri: http://knative-labs-service.knative-labs.svc.cluster.local/ce/example-07/no-reply
  ```
 **Knative release version**
Knative v1.2 (installed with kn-quickstart v1.2)
eventing-kafka/channels/distributed v1.2
eventing-kafka-broker v1.2.1

**Additiona Context**
- Although I didn't describe it, the KafkaBroker and triggers works after setting up both. 
- Only new triggers for MTChannelBasedBroker (Kafka channel/distributed) created after installing `eventing-kafka-broker` gets stuck.. Existing triggers created before continue to function after.

The following shows `eventing-kafka-broker` installation changing existing CRDs that were already installed before which I unexpected.

```
$ kubectl apply -f https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.1/eventing-kafka-controller.yaml
configmap/kafka-broker-config created
configmap/kafka-channel-config created
customresourcedefinition.apiextensions.k8s.io/kafkachannels.messaging.knative.dev configured
customresourcedefinition.apiextensions.k8s.io/consumers.internal.kafka.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/consumergroups.internal.kafka.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/kafkasinks.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/kafkasources.sources.knative.dev configured
clusterrole.rbac.authorization.k8s.io/eventing-kafka-source-observer configured
configmap/kafka-config-logging created
configmap/config-tracing configured
clusterrole.rbac.authorization.k8s.io/knative-kafka-addressable-resolver created
clusterrole.rbac.authorization.k8s.io/knative-kafka-channelable-manipulator created
clusterrole.rbac.authorization.k8s.io/kafka-controller created
serviceaccount/kafka-controller created
clusterrolebinding.rbac.authorization.k8s.io/kafka-controller created
clusterrolebinding.rbac.authorization.k8s.io/kafka-controller-addressable-resolver created
deployment.apps/kafka-controller created
clusterrole.rbac.authorization.k8s.io/kafka-webhook-eventing created
serviceaccount/kafka-webhook-eventing created
clusterrolebinding.rbac.authorization.k8s.io/kafka-webhook-eventing created
mutatingwebhookconfiguration.admissionregistration.k8s.io/defaulting.webhook.kafka.eventing.knative.dev created
secret/kafka-webhook-eventing-certs created
validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.kafka.eventing.knative.dev created
deployment.apps/kafka-webhook-eventing created
service/kafka-webhook-eventing created
```
