### ISSUE TITLE
Do not ship assumed default values for a kafka cluster

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#1939]
**Problem**

For the control plane the release artifacts ship the `kafka-broker-config` CM. With this content:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: knative-eventing
  labels:
    kafka.eventing.knative.dev/release: "devel"
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"
  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9092"
```

IMO this more handy for us, doing development, rather than in production.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.
