### ISSUE TITLE
KafkaSource fails to connect to Confluent Cloud using SASL_SSL

### ISSUE THREAD

**Issue by niels-busch-maersk** [knative-sandbox/eventing-kafka-broker#1952]
**Describe the bug**

When configuring Kafka source to connect to Confluent Cloud with SASL_SSL I get the following error message:

`topics [myTopic] not present or invalid: error getting sarama config: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`

 **Expected behavior**

I expect events forwarded via KafkaSource to the configured sink.

 **To Reproduce**

I created a secret:
```
kubectl create secret generic kafka-auth \
--from-literal=security.protocol=SASL_SSL \
--from-literal=sasl.mechanism=PLAIN \
--from-literal=user=myUser \
--from-literal=password=myPassword
```

I created a service to be used as sink:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - # This corresponds to
          # https://github.com/knative/eventing/tree/main/cmd/event_display/main.go
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
```

And configured the KafkaSource:
```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: myConsumerGroup
  bootstrapServers:
  - myServer.westeurope.azure.confluent.cloud:9092
  topics:
  - myTopic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
  net:
    sasl:
      enable: true
      password:
        secretKeyRef:
          key: password
          name: kafka-auth
      type:
        secretKeyRef:
          key: sasl.mechanism
          name: kafka-auth
      user:
        secretKeyRef:
          key: user
          name: kafka-auth
```

 **Knative release version**

1.2.0

 **Additional context**

What am I doing wrong?
