### ISSUE TITLE
metadata.finalizers: Invalid value: name part must be no more than 63 characters

### ISSUE THREAD

**Issue by r00ta** [knative-sandbox/eventing-kafka-broker#1970]
**Describe the bug**
When I create a Knative eventing broker using a configmap with name `ob-46b35be1-0165-441b-9158-a7ec08ad7a97` and namespace `ob-1608dc1f-4139-49c5-ae22-afe73ed807d7` the Broker fails with 
```
 reason: >-
        failed to add finalizer to ConfigMap
        ob-1608dc1f-4139-49c5-ae22-afe73ed807d7/ob-46b35be1-0165-441b-9158-a7ec08ad7a97:
        ConfigMap "ob-46b35be1-0165-441b-9158-a7ec08ad7a97" is invalid:
        metadata.finalizers: Invalid value:
        "kafka.brokers.eventing.knative.dev/ob-1608dc1f-4139-49c5-ae22-afe73ed807d7-ob-46b35be1-0165-441b-9158-a7ec08ad7a97":
        name part must be no more than 63 characters
```

 **Expected behavior**
I think sometimes it is reasonable to use a uuid for a name and a namespace, so I would expect this to work. I think the prefix `kafka.brokers.eventing.knative.dev` is slightly longer than needed. 

 **To Reproduce**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
  namespace: ob-1608dc1f-4139-49c5-ae22-afe73ed807d7
data:
  auth.secret.ref.name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
  bootstrap.servers: REDACTED
  default.topic.partitions: '10'
  default.topic.replication.factor: '3'
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
  namespace: ob-1608dc1f-4139-49c5-ae22-afe73ed807d7
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: ob-468c0030-c45e-4ded-8c79-08cb1e455085
    namespace: ob-1608dc1f-4139-49c5-ae22-afe73ed807d7
```

 **Knative release version**
release-1.1
 **Additional context**
Add any other context about the problem here such as proposed priority
