### ISSUE TITLE
Old golang kafka source did not require type secretKeyRef for SASL but seems to require now?

### ISSUE THREAD

**Issue by aslom** [knative-sandbox/eventing-kafka-broker#2117]
**Describe the bug**
Old golang kafka source did not require type secretKeyRef for SASL but seems to require now?

 **Expected behavior**
Existing kafka source should work without changes

 **To Reproduce**
Example Kafka Source that worked before:

```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-es10
spec:
  consumerGroup: kafkaes10j27c
  bootstrapServers:
  - kafka-1.mh-lbnyvywmvwwvpcmssqgl-4c201a12d7add7c99d2b22e361c6f175-0000.us-south.containers.appdomain.cloud:9093
  topics:
  - e2et10
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-secret-es
          key: user
      password:
        secretKeyRef:
          name: kafka-secret-es
          key: password
    tls:
      enable: true
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: hello-display
```

With this YAML setup I got no events - I saw in kafka data-plane logs:

```
{"@timestamp":"2022-04-21T18:44:04.623Z","@version":"1","message":"Failed to reconcile [onNewEgress] egress  id=077c039a-34fb-4a51-a214-94298dd06f5b consumerGroup=kafkaes10j27c destination=http://hello-display.k9.svc.cluster.local/","logger_name":"dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerImpl","thread_name":"vert.x-eventloop-thread-0","level":"ERROR","level_value":40000,"stack_trace":"io.vertx.core.impl.NoStackTraceThrowable: Security protocol SASL_SSL: invalid SASL mechanism, expected SCRAM-SHA-256, SCRAM-SHA-512 or PLAIN got null\n","id":"077c039a-34fb-4a51-a214-94298dd06f5b","consumerGroup":"kafkaes10j27c","destination":"http://hello-display.k9.svc.cluster.local/"}
```

Kafak source status was showing OK:

```
k get kafkasources.sources.knative.dev ; date
NAME             TOPICS           BOOTSTRAPSERVERS                                                                                                        READY   REASON   AGE
kafka-es10       ["e2et10"]       ["kafka-1.mh-lbnyvywmvwwvpcmssqgl-4c201a12d7add7c99d2b22e361c6f175-0000.us-south.containers.appdomain.cloud:9093"]      True             3h15m
```

After adding type to Kafka source I have got all events in hello-display sink:

```
      type:
        secretKeyRef:
          name: kafka-secret-es
          key: type
```

 **Knative release version**

1.4 with V2

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by steven0711dong** [comment]
@aslom Yeah, I think what I saw is similar. With the new eventing-kafka-broker, we are required to add an additional field:
```
type:
        secretKeyRef:
          name: kafka-secret-es
          key: type
```
And we also need to create one more field in the referenced secret. This was not required on our old CR. The error message I saw was a little different though. The error I saw was something like this. 
```
[protocol SASL_SSL] key sasl.mechanism is required. 
```
