### ISSUE TITLE
KafkaChannel in MT broker

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2122]
Using the channel in the MT Broker, I get this dispatcher log:

```
Apr 25, 2022 7:37:42 AM io.vertx.core.net.impl.ConnectionBase
SEVERE: Multiple Content-Length values found: [19, 19]
{"@timestamp":"2022-04-25T07:37:42.894Z","@version":"1","message":"failed to send event to subscriber target=http://broker-filter.knative-eventing.svc.cluster.local/triggers/default/processor/27490a39-007c-46c3-9c5a-caeb2aa97ed7","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.impl.http.WebClientCloudEventSender","thread_name":"vert.x-eventloop-thread-0","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalArgumentException: Multiple Content-Length values found: [19, 19]\n\tat io.netty.handler.codec.http.HttpUtil.normalizeAndGetContentLength(HttpUtil.java:599)\n\tat io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:673)\n\tat io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:281)\n\tat io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:238)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)\n\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n","target":"http://broker-filter.knative-eventing.svc.cluster.local/triggers/default/processor/27490a39-007c-46c3-9c5a-caeb2aa97ed7"}
```

**Comment by matzew** [comment]
I use a "processor", like:

```java
package functions;

import io.quarkus.funqy.Funq;
import io.quarkus.funqy.knative.events.CloudEvent;
import io.quarkus.funqy.knative.events.CloudEventBuilder;

import java.util.UUID;

public class Function {

    @Funq
    public CloudEvent<Output> function(CloudEvent<Input> input) {

        // work with the received Cloud event:
        // do some sort of processing with it...
        System.out.println(" We got: " + input);

        // create some other business object:
        Output output = new Output("HEllo");

        // return the object to the broker,
        // wrapped as a cloud event:

        CloudEvent<Output> response = CloudEventBuilder.create()
                .source("/service/processors/1/random")
                .type("io.openshift.smart.event.processor")
                .id(UUID.randomUUID().toString())
                .build(output);

        System.out.println("We sent back: " + response);

        return response;
    }
}
```

and a receiver (the canonical `event-display`).

Here is the manifests:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: processor
spec:
  selector:
    app: processor
  ports:
    - port: 80
      protocol: TCP
      targetPort: processor
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: processor
  labels:
    app: processor
spec:
  containers:
  - name: processor
    image: docker.io/matzew/processor-demo:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
      name: processor
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  selector:
    app: receiver
  ports:
    - port: 80
      protocol: TCP
      targetPort: receiver
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  containers:
  - name: receiver
    image: quay.io/openshift-knative/knative-eventing-sources-event-display
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
      name: receiver
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: processor
spec:
  broker: my-kafkachannel-advanced-broker
  filter:
    attributes:
      smartevent: super-duper-event-extension
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: receiver
spec:
  broker: my-kafkachannel-advanced-broker
  filter:
    attributes:
      type: io.openshift.smart.event.processor 
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: receiver
---
```

for the broker I use this config: https://github.com/openshift-knative/eventing-hyperfoil-benchmark/blob/main/testcases/broker/eventing-broker/broker-kc-advanced-config/100-broker.yaml

**Comment by aliok** [comment]
> for the broker I use this config: https://github.com/openshift-knative/eventing-hyperfoil-benchmark/blob/main/testcases/broker/eventing-broker/broker-kc-advanced-config/100-broker.yaml

When I use that I get this:

```
❯ k get brokers -A                                                                                                                                       ─╯
NAMESPACE   NAME                              URL   AGE     READY   REASON
default     my-kafkachannel-advanced-broker         2m30s   False   unable to build topic config from configmap: error validating topic config from configmap invalid configuration - numPartitions: 0 - replicationFactor: 0 - bootstrapServers: [] - ConfigMap data: map[channelTemplateSpec:apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
spec:
    numPartitions: 10
    replicationFactor: 3
    delivery:
      retry: 12
      backoffPolicy: exponential
      backoffDelay: PT1S] - ConfigMap data: map[channelTemplateSpec:apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
spec:
    numPartitions: 10
    replicationFactor: 3
    delivery:
      retry: 12
      backoffPolicy: exponential
      backoffDelay: PT1S]
```

cc @pierDipi

**Comment by aliok** [comment]
I don't get it....

When I add the broker class annotation, this time I don't see any reaction in any of the controllers...


```
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
```

**Comment by matzew** [comment]
@aliok  did you install it via `hack/run.sh` ? 
If so, that does setup the `Kafka` brokers to be the default:

```bash
k get cm config-br-defaults -nknative-eventing -o yaml
apiVersion: v1
data:
  default-br-config: |
    clusterDefault:
      brokerClass: Kafka
      apiVersion: v1
      kind: ConfigMap
      name: kafka-broker-config
      namespace: knative-eventing
kind: ConfigMap
...
```

The referenced broker config does _not_ have any annotation, so it assumes that the broker default is the `MTChannelBasedBroker`.

**Comment by matzew** [comment]
On `main`, the `receiver` still does NOT receive a message.

But I am seeing different logs:

```bash
{"@timestamp":"2022-04-25T12:31:47.433Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-1 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 1 rack: null)], epoch=0}} to node my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 1 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.433Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Built incremental fetch (sessionId=152424680, epoch=328) for node 1. Added 0 partition(s), altered 0 partition(s), removed 0 partition(s) out of 3 partition(s)","logger_name":"org.apache.kafka.clients.FetchSessionHandler","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.433Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Sending READ_UNCOMMITTED IncrementalFetchRequest(toSend=(), toForget=(), implied=(knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-7, knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-4, knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-1)) to broker my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 1 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.433Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Sending FETCH request with header RequestHeader(apiKey=FETCH, apiVersion=12, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1057) and timeout 30000 to node 1: FetchRequestData(clusterId=null, replicaId=-1, maxWaitMs=500, minBytes=1, maxBytes=52428800, isolationLevel=0, sessionId=152424680, sessionEpoch=328, topics=[], forgottenTopicsData=[], rackId='')","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Received FETCH response from node 2 for request with header RequestHeader(apiKey=FETCH, apiVersion=12, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1055): FetchResponseData(throttleTimeMs=0, errorCode=0, sessionId=1809965895, responses=[])","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Node 2 sent an incremental fetch response with throttleTimeMs = 0 for session 1809965895 with 0 response partition(s), 4 implied partition(s)","logger_name":"org.apache.kafka.clients.FetchSessionHandler","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-9 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)], epoch=0}} to node my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-3 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)], epoch=0}} to node my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-6 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)], epoch=0}} to node my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-0 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)], epoch=0}} to node my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Built incremental fetch (sessionId=1809965895, epoch=328) for node 2. Added 0 partition(s), altered 0 partition(s), removed 0 partition(s) out of 4 partition(s)","logger_name":"org.apache.kafka.clients.FetchSessionHandler","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Sending READ_UNCOMMITTED IncrementalFetchRequest(toSend=(), toForget=(), implied=(knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-9, knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-3, knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-6, knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-0)) to broker my-cluster-kafka-2.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.446Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Sending FETCH request with header RequestHeader(apiKey=FETCH, apiVersion=12, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1058) and timeout 30000 to node 2: FetchRequestData(clusterId=null, replicaId=-1, maxWaitMs=500, minBytes=1, maxBytes=52428800, isolationLevel=0, sessionId=1809965895, sessionEpoch=328, topics=[], forgottenTopicsData=[], rackId='')","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.763Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Sending Heartbeat request with generation 1 and member id consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2-9b1f68d8-0ed4-47b0-b6e6-bbb6d7747979 to coordinator my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2147483646 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.AbstractCoordinator","thread_name":"kafka-coordinator-heartbeat-thread | kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.764Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Sending HEARTBEAT request with header RequestHeader(apiKey=HEARTBEAT, apiVersion=4, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1059) and timeout 30000 to node 2147483646: HeartbeatRequestData(groupId='kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37', generationId=1, memberId='consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2-9b1f68d8-0ed4-47b0-b6e6-bbb6d7747979', groupInstanceId=null)","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"kafka-coordinator-heartbeat-thread | kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.772Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Received HEARTBEAT response from node 2147483646 for request with header RequestHeader(apiKey=HEARTBEAT, apiVersion=4, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1059): HeartbeatResponseData(throttleTimeMs=0, errorCode=0)","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.773Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Received successful Heartbeat response","logger_name":"org.apache.kafka.clients.consumer.internals.AbstractCoordinator","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.935Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Received FETCH response from node 1 for request with header RequestHeader(apiKey=FETCH, apiVersion=12, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1057): FetchResponseData(throttleTimeMs=0, errorCode=0, sessionId=152424680, responses=[])","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.936Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Node 1 sent an incremental fetch response with throttleTimeMs = 0 for session 152424680 with 0 response partition(s), 3 implied partition(s)","logger_name":"org.apache.kafka.clients.FetchSessionHandler","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.937Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Received FETCH response from node 0 for request with header RequestHeader(apiKey=FETCH, apiVersion=12, clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, correlationId=1056): FetchResponseData(throttleTimeMs=0, errorCode=0, sessionId=1806667037, responses=[])","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"kafka-coordinator-heartbeat-thread | kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.937Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Node 0 sent an incremental fetch response with throttleTimeMs = 0 for session 1806667037 with 0 response partition(s), 3 implied partition(s)","logger_name":"org.apache.kafka.clients.FetchSessionHandler","thread_name":"kafka-coordinator-heartbeat-thread | kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.945Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-8 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092 (id: 0 rack: null)], epoch=0}} to node my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092 (id: 0 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-04-25T12:31:47.945Z","@version":"1","message":"[Consumer clientId=consumer-kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37-2, groupId=kafka.default.kafkachannel-advanced-broker-kne-trigger.2da06c26-0581-4caa-a97f-028b7f893e37] Added READ_UNCOMMITTED fetch request for partition knative-messaging-kafka.default.kafkachannel-advanced-broker-kne-trigger-7 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 1 rack: null)], epoch=0}} to node my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 1 rack: null)","logger_name":"org.apache.kafka.clients.consumer.internals.Fetcher","thread_name":"vert.x-kafka-consumer-thread-1","level":"DEBUG","level_value":10000}
...
...
...
...
...
```

**Comment by aliok** [comment]
> @aliok did you install it via hack/run.sh ?
> If so, that does setup the Kafka brokers to be the default:

Yes, I know that. I tried 3 things:
- MTbroker as default broker and no annotation on the broker --> no reaction from the controller
- KafkaChannel as default broker and MTBroker annotation on the broker --> again, no reaction
- MTbroker as default broker and MTBroker annotation on the broker --> no reaction from the controller

Something is off.

But I am now trying with OpenShift midstream 1.2

**Comment by matzew** [comment]
FWIW, the `hack/run.sh` does not install the IMC/MTChannelBasedBroker things. I did `ko apply -f ` them from eventing upstream main

**Comment by matzew** [comment]
@aliok a few questions:

* `failed to send event to subscriber target=http://broker-filter.knative-eventing.svc.cluster.local/triggers/default/processor`: Why is it sending to there? The service of that receiver does return a CloudEvent. (did we log the actual value of the CloudEvent, that's being failed?  (e.g. is it the initial one, or the one returned)?
* Does the channel function when a service from a subscriber does return some CloudEvent, to be sent down to a reply channel?

**Comment by matzew** [comment]
FWIW, reply channel works (e.g. with):

```yaml
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: process-sub
  namespace: default
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: process-channel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: processor
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: KafkaChannel
      name: receive-channel
```
