### ISSUE TITLE
Unable to configure user.skip for Kafka Source

### ISSUE THREAD

**Issue by aslom** [knative-sandbox/eventing-kafka-broker#2162]
**Describe the bug**
I think it should be possible but I may be missing the right place to put it in YAML?

Getting error

```
status:
  conditions:
  - lastTransitionTime: "2022-05-05T19:06:41Z"
    status: Unknown
    type: ConfigMapUpdated
  - lastTransitionTime: "2022-05-05T19:06:41Z"
    message: 'failed to initialize consumer group offset: failed to create Admin client
      config: [protocol SSL] required user key (key: user.key) - use "user.skip: true"
      to disable client auth'
    reason: InitializeOffset
    status: "False"
    type: ConsumerGroup
  - lastTransitionTime: "2022-05-05T19:06:41Z"
    message: Did you install the data plane for this component?
    reason: Data plane not available
    status: "False"
    type: DataPlaneAvailable
  - lastTransitionTime: "2022-05-05T19:06:41Z"
    status: Unknown
    type: InitialOffsetsCommitted
  - lastTransitionTime: "2022-05-05T19:06:52Z"
    message: 'failed to initialize consumer group offset: failed to create Admin client
      config: [protocol SSL] required user key (key: user.key) - use "user.skip: true"
      to disable client auth'
    reason: InitializeOffset
    status: "False"
    type: Ready
```

Looked docs in
https://knative.dev/docs/eventing/sources/kafka-source/#connecting-to-a-tls-enabled-kafka-broker
https://knative.dev/docs/eventing/sinks/kafka-sink/#authentication-using-sasl-without-encryption

Created secret
```
kubectl create secret generic strimzi8-secret --from-literal=protocol=SSL --from-file=ca.crt=setup/strimzi-ca8.pem --from-literal=user.skip=true
```

Tried

```
spec:
  net:
    tls:
      enable: true
      user.skip: true
      caCert:
        secretKeyRef:
          key: ca.crt
          name: strimzi8-secret
  consumerGroup: kafka-src-grp100e
```

and

```
spec:
  net:
    tls:
      enable: true
      user.skip:
        secretKeyRef:
          key: user.skip
          name: strimzi8-secret
      caCert:
        secretKeyRef:
          key: ca.crt
          name: strimzi8-secret
  consumerGroup: kafka-src-grp100e
```

 **Expected behavior**
I should be able to use Kafka broker with TLS without client auth

 **To Reproduce**
Try to configure Kafka source as documented in https://knative.dev/docs/eventing/sources/kafka-source/#connecting-to-a-tls-enabled-kafka-broker
without specifying `cert` and `key` - remove those sections to get

```
piVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
 name: kafka-source-with-tls-no-auth
spec:
 net:
   tls:
     enable: true
     caCert:
       secretKeyRef:
         key: caroot.pem
         name: cacert
 consumerGroup: knative-group
 bootstrapServers:
 - my-secure-kafka-bootstrap.kafka:443
 topics:
 - knative-demo-topic
 sink:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: event-display
```

 **Knative release version**

 **Additional context**
I veirified that I can access that Strimzi form outside using TLS wit Kafka CLI:

```
cat strimzi-tls.properties
security.protocol=SSL
ssl.truststore.location=client.truststore.jks
ssl.truststore.password=test1234
```

```
./bin/kafka-topics.sh --command-config strimzi-tls.properties  --describe --topic knative-demo-topic --bootstrap-server my-cluster-kafka-bootstrap-kafka....-0000.us-south.containers.appdomain.cloud:443
Topic: knative-demo-topic	TopicId: 27_M0zOfQEadyaGeeG6OWw	PartitionCount: 1	ReplicationFactor: 1	Configs: min.insync.replicas=2,segment.bytes=1073741824,retention.ms=7200000,message.format.version=3.0-IV1
	Topic: knative-demo-topic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
```
