### ISSUE TITLE
Broker finalizer stuck if "auth.secret.ref.name" Secret deleted before namespace containing Broker

### ISSUE THREAD

**Issue by maschmid** [knative-sandbox/eventing-kafka-broker#2211]
**Describe the bug**
Deleting a namespace with a Broker in it blocks deletion, with the Broker's finalizer apparently stuck if its `auth.secret.ref.name` Secret is deleted first.

The controller repeats a "Reconcile error"

```
{"level":"error","ts":"2022-05-19T15:44:51.383Z","logger":"kafka-broker-controller","caller":"controller/controller.go:559","msg":"Reconcile error","knative.dev/pod":"kafka-controller-7ffbbbc6dc-6qz4w","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.broker.Reconciler","knative.dev/kind":"eventing.knative.dev.Broker","knative.dev/traceid":"01fbe208-356e-43df-86a8-4768eef2ae24","knative.dev/key":"foobar/broker","duration":0.01480933,"error":"failed to get secret: failed to get secret foobar/broker-secret: secrets \"broker-secret\" not found","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/controller/controller.go:559\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/controller/controller.go:536\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\t/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/controller/controller.go:484"}
```

 **Expected behavior**
Order of deletion should not matter. Broker's finalizer should deal with the Secret already deleted when its namespace is already undergoing deletion.

 **To Reproduce**
Assuming a Strimzi-installed Kafka in `kafka` namespace with 

```
      - authentication:
          type: scram-sha-512
        name: saslplain
        port: 9095
        tls: false
        type: internal
```
and a KafkaUser `my-sasl-user` user.

In a `foobar` namespace, replace `<password>`, creating the secret:

```
kubectl create secret --namespace foobar generic broker-secret \
  --from-literal=protocol=SASL_PLAINTEXT \
  --from-literal=sasl.mechanism=SCRAM-SHA-512 \
  --from-literal=user=my-sasl-user \
  --from-literal=password=<password>
```

```
kubectl create -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: foobar
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"
  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9095"
  auth.secret.ref.name: broker-secret
EOF

kubectl create -f - <<EOF
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: broker
  namespace: foobar
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: foobar
EOF

```

Delete the Secret and then the whole namespace:

```
kubectl delete secret broker-secret -n foobar
kubectl delete namespace foobar
```

 **Knative release version**
1.2.3

 **Additional context**
Installed via OpenShift Serverless operator, current `main` https://github.com/openshift-knative/serverless-operator
