### ISSUE TITLE
Update Kafka CR and Kafka user setup for integration tests

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2289]
**Problem**

With recent versions of Strimzi _and_ making usage of `KafkaUsers` CRD, we must have the following on the `Kafkas` CR file:
```yaml
...
    authorization:
      type: simple
...
```

One option could be adding `ANONYMOUS` on the CR as well:

```yaml
...
    authorization:
      type: simple
      superUsers:
        - ANONYMOUS  
...
```

This way, any connection without authentication will be ANONYMOUS and will be able to do everything...

**Exit Criteria**
We should revisit our tests to make sure that without both( no authentication and no authorization) we test on port 9092
And with _both enabled_ (authentication and authorization) we test on port 9093 for instance
