### ISSUE TITLE
Broker cannot be deleted if config is not right

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka-broker#2536]
**Describe the bug**
Broker cannot be deleted 
- If `spec.config` configmap does not exist.
- If `spec.config.kind` is not `configmap` (this is to be handled by the webhook, part of #2537 )
- Bootstrap server is not reachable.

In general, if there is anything wrong in the config, we cannot delete the broker.

 **Expected behavior**
Deletion of the broker should work anyway.

 **To Reproduce**

Created 2 tests that fail here: https://github.com/aliok/eventing-kafka-broker/tree/2022-08-26-broker-stuck
1. Create a Broker resource with `spec.config` pointing to something that doesnt exist --> cannot delete broker
2. Create a Broker resource with `bootstrapServer` in config is pointing to an unreachable Kafka cluster --> cannot delete broker

To reproduce manually, create a broker like:

```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: default
  namespace: default
spec:
  # Configuration specific to this broker.
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: nonononono
```

Delete the broker:
```
kubectl delete broker -n default default
```

Broker stays in status:
```
NAMESPACE   NAME       URL   AGE   READY   REASON
default     default3         7s    False   failed to get configmap foo/kafka-broker-config: configmap "kafka-broker-config" not found
```

Error in controller:
```
{"level":"info","ts":"2022-08-22T07:47:06.585Z","logger":"kafka-broker-controller.event-broadcaster","caller":"record/event.go:285","msg":"Event(v1.ObjectReference{Kind:\"Broker\", Namespace:\"default\", Name:\"default3\", UID:\"13a5591a-7b73-4ed0-939f-f4a7e6895c5a\", APIVersion:\"eventing.knative.dev/v1\", ResourceVersion:\"3366919\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' failed to resolve broker config: failed to get configmap foo/kafka-broker-config: configmap \"kafka-broker-config\" not found","commit":"c90b655","knative.dev/pod":"kafka-controller-79785864cc-8z88q"}
```

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority
