### ISSUE TITLE
Broker validation webhook is not triggered

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka-broker#2537]
**Describe the bug**
Broker validation webhook is not triggered

 **Expected behavior**
Broker validation webhook is to be triggered

 **To Reproduce**
Create a broker with invalid configuration (`spec.config.kind` is not a `ConfigMap`):

```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: default3
  namespace: default
spec:
  config:
    apiVersion: v1
    kind: Fuk
    name: kafka-broker-config
    namespace: knative-eventing
```

Broker is not rejected by the webhook.

I added some log statements to the validation code (https://github.com/knative-sandbox/eventing-kafka-broker/blob/2133e8c7068c935aeb07304770f0c3962755d564/control-plane/pkg/apis/eventing/v1/broker_validation.go#L71-L73) and I saw nothing is printed.

```
kubectl get brokers -A
NAMESPACE   NAME       URL   AGE    READY   REASON
default     default3         106s   False   supported config Kind: ConfigMap - got Fuk
```

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority
