### ISSUE TITLE
No existing ConfigMap prevents broker deletion

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2566]
Sub issue from https://github.com/knative-sandbox/eventing-kafka-broker/issues/2536

having a broker with a config that does not exist:https://github.com/knative-sandbox/eventing-kafka-broker/issues/2536

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: my-demo-kafka-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: blub
```

Keeps stuck in deletion of the broker, even it has the `READY` status set to `false`:

```
➜  ~ k get brokers.eventing.knative.dev -A 
NAMESPACE   NAME                   URL   AGE     READY   REASON
default     my-demo-kafka-broker         3m46s   False   failed to get configmap blub/kafka-broker-config: configmap "kafka-broker-config" not found
```
