### ISSUE TITLE
Unreachable Kafka cluster prevents broker deletion

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2569]
Sub issue from https://github.com/knative-sandbox/eventing-kafka-broker/issues/2536

having a broker with a config for a Kafka cluster that does not exist, or is not reachable:

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: my-broken-kafka-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: my-broken-kafka-broker-config
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-broken-kafka-broker-config
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"
  bootstrap.servers: "matzew-test.kafka.not.existing:443"

```

Will go to a `false` `READY` state:

```
➜  ~ k get brokers.eventing.knative.dev -A 
NAMESPACE   NAME                     URL   AGE   READY   REASON
default     my-broken-kafka-broker         13m   False   cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: dial tcp: lookup matzew-test.kafka.not.existing:443 on 10.xx.xx:xx: no such host
```

But that none-ready broker is than stuck for deleting, and finalizeKind does not exit correctly
