### ISSUE TITLE
kafka dispatcher "SEVERE: Unhandled exception" when a sink returns a non-cloudevent response with an error status

### ISSUE THREAD

**Issue by maschmid** [knative-sandbox/eventing-kafka-broker#2594]
**Describe the bug**
Having a sink returning a 404 status with a body

```
<!doctype html>
<html>
<head>
    <title>Error Page(tm)</title></head>
<body>
<p>Quoth the server, 404!
</body></html>
```

causes an Unhandled exception in the kafka dispatcher

```
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: only ' ' and '\t' are allowed after '\n'
```

Furthermore, the event that was sent to the sink is not processed further (there is no attempt at sending it to a deadLetterSink when this error occured)

 **Expected behavior**
Dispatcher should not log an "SEVERE: Unhandled exception" and should retry a retry-able status code from a sink even if it contains any random response body

 **To Reproduce**
With an existing Kafka Broker config, it can be reproduce by something like
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker
  annotations:
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: broker
  delivery:
    backoffDelay: PT1S
    backoffPolicy: linear
    deadLetterSink:
      ref:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: KafkaSink
        name: dlq-sink
    retry: 5
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: subscription
spec:
  broker: broker
  subscriber:
    uri: http://example.com/doesnotexist
```

 **Knative release version**
1.4

 **Additional context**
Using OpenShift Serverless 1.25 from current `main` https://github.com/openshift-knative/serverless-operator
