### ISSUE TITLE
External managed topic on Azure Event Hub is unable to be consumed from Kafka Broker

### ISSUE THREAD

**Issue by marcjimz** [knative-sandbox/eventing-kafka-broker#2692]
I'm running an Azure Event Hub with scoped credentials (can read) but my broker is failing on setting up the Kafka admin client. I am able to consume events using custom Python code and other frameworks (Argo EventSources) but the broker class is limiting my access on this. 

I am hitting this error: https://github.com/knative-sandbox/eventing-kafka-broker/blob/6c7d57ef751c6e6502a38759ea8cb8f274623506/control-plane/pkg/reconciler/broker/broker.go#L277

I have setup my configMap:

```yaml
apiVersion: v1
data:
  auth.secret.ref.name: knative-eventing-poc-main-secret
  bootstrap.servers: <INSTANCE>.servicebus.windows.net:9093
  default.topic.partitions: "4"
  default.topic.replication.factor: "3"
kind: ConfigMap
metadata:
  name: knative-eventing-poc-main-config
```

with secret (decoded):

```yaml
password: Endpoint=sb://<INSTANCE>.servicebus.windows.net/;SharedAccessKeyName=ak-01;SharedAccessKey=<KEY>;EntityPath=<EP>
protocol: SASL_SSL 
sasl.mechanism: PLAIN 
user: $ConnectionString
```

I'm constantly reproducing errors:

```sh
'Warning' reason: 'InternalError' failed to get contract configuration: cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: dial tcp 52.168.117.34:9093: i/o timeout
```

I've been able to confirm I can reach the topics fine on the same cluster, same nodes, etc. so networking is ruled out.
