### ISSUE TITLE
dataplane cannot connect to kafka with "Encryption using SSL without client authentication"

### ISSUE THREAD

**Issue by maschmid** [knative-sandbox/eventing-kafka-broker#2708]
**Describe the bug**
Following  https://knative.dev/docs/eventing/sinks/kafka-sink/#encryption-using-ssl-without-client-authentication

using Kafka with Strimzi, with listener:
```
      - name: tlsnone
        port: 9096
        tls: true
        type: internal
```
a secret with
```
data:
  ca.crt: <some base64-encoded cert>==
  protocol: U1NM
  user.skip: dHJ1ZQ==
```
and a kafkasink
```
apiVersion: eventing.knative.dev/v1alpha1
kind: KafkaSink
metadata:
  name: tls-no-auth
  namespace: foobar
spec:
  auth:
    secret:
      ref:
        name: tls-no-auth
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9096
  contentMode: structured
  topic: foobar-topic
```
a KafkaSink with such configuration doesn't become Ready due to ProbeStatus (dataplane cannot connect to Kafka)

The problem seems to be due to KubernetesCredentials.java not base64 decoding the "user.skip"

https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java#L80-L96

 **Expected behavior**
"Encryption using SSL without client authentication" should work as documented 

 **To Reproduce**
see above

 **Knative release version**
1.4

 **Additional context**
on OpenShift, deployed using Serverless operator https://github.com/openshift-knative/serverless-operator/tree/release-1.25
