### ISSUE TITLE
KafkaChannel - EOF while trying to use SASL with Azure Event Hubs

### ISSUE THREAD

**Issue by mwieczorkiewicz** [knative-sandbox/eventing-kafka-broker#2766]
**Describe the bug**
When using Kafka Eventing and trying to use Azure Event Hubs' Kafka endpoint configuring KafkaChannel to leverage Azure Event Hubs results in EOF related errors. 

Broker and KafkaSource work exactly as intended (using identical settings), so I suspect there might be something off with the way I am trying to configure it.

SASL secret (`knative-eventing/kafka-ch-sasl-secret`):
```
apiVersion: v1
data:
  password: {EVENT_HUB_CONNECTIONSTRING}
  protocol: SASL_SSL
  sasl.mechanism: PLAIN
  user: $ConnectionString
kind: Secret
metadata:
  name: kafka-ch-sasl-secret
  namespace: knative-eventing
type: Opaque
```

Used settings `kafka-channel-config`:
```
apiVersion: v1
data:
  auth.secret.ref.name: kafka-ch-sasl-secret
  auth.secret.ref.namespace: knative-eventing
  bootstrap.servers: {EVENT_HUB_ADDR}
kind: ConfigMap
metadata:
  name: kafka-channel-config
  namespace: knative-eventing
```

Controller logs:

```
controller {"level":"error","ts":"2022-11-03T08:42:22.683Z","logger":"kafka-broker-controller","caller":"controller/controller.go:566","msg":"Reconcile error","knative.dev/pod":"kafka-controller-5859d85477-lbrxv","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.channel.Reconciler","knative.dev/kind":"messaging.knative.dev.KafkaChannel","knative.dev/traceid":"080716e6-dac7-4778-959d-aee79d350bbb","knative.dev/key":"test-ns/test-sequence-kn","duration":0.815566277,"error":"failed to create topic: knative-messaging-kafka.test-ns.test-sequence-kn: cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: EOF","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220705130606-e60d250dc637/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220705130606-e60d250dc637/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220705130606-e60d250dc637/controller/controller.go:491"}
controller {"level":"info","ts":"2022-11-03T08:42:22.683Z","logger":"kafka-broker-controller.event-broadcaster","caller":"record/event.go:285","msg":"Event(v1.ObjectReference{Kind:\"KafkaChannel\", Namespace:\"test-ns\", Name:\"test-sequence-kn\", UID:\"f0c1b2fc-a8e9-427a-a1e3-040e1c18b320\", APIVersion:\"messaging.knative.dev/v1beta1\", ResourceVersion:\"109374008\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' failed to create topic: knative-messaging-kafka.test-ns.test-sequence-kn: cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: EOF","knative.dev/pod":"kafka-controller-5859d85477-lbrxv"}
```

 **Expected behavior**
KafkaChannel behaving as KafkaSource and KafkaBroker

 **To Reproduce**
Create new Azure Event Hub, create secrets with credentials, configure KafkaChannel to use Event Hubs.  Can be replicated in a fresh `kind` cluster. 

 **Knative release version**
1.6 

 **Eventing Kafka Broker release version**
1.6.10 (observed also on 1.8.x in `kind` local cluster)
