### ISSUE TITLE
Broker ready but HTTP code 503 returned because of NOT_ENOUGH_REPLICAS error in `kafka-broker-receiver`

### ISSUE THREAD

**Issue by febus982** [knative-sandbox/eventing-kafka-broker#2805]
**Describe the bug**
When sending a message to a broker marked as ready, `kafka-broker-receiver` throws a NOT_ENOUGH_REPLICAS and the ingress entrypoint returns HTTP code 503.

I am able to see the topic created in the kafka cluster so I think authentication is fine.

From the logs it looks like some statefulset might be missing (from the `-0` suffix) but I wasn't able to find other errors.

I am not able to see any pod or stateful set resembling the `REDACTED` name in the receiver error. 

 **Expected behavior**
Event sent to the topic and 200 returned.

 **To Reproduce**
Steps to reproduce the behavior. NOT SURE

 **Knative release version**
Knative: 1.8.0
Broker version: 1.8.3 (same behaviour on 1.8.2)

 **Additional context**
`kafka-broker-receiver` logs
```
{"@timestamp":"2022-11-23T15:39:44.966Z","@version":"1","message":"[Producer clientId=producer-6] Got error produce response with correlation id 1201 on topic-partition REDACTED-0, retrying (2147482468 attempts left). Error: NOT_ENOUGH_REPLICAS","logger_name":"org.apache.kafka.clients.producer.internals.Sender","thread_name":"kafka-producer-network-thread | producer-6","level":"WARN","level_value":30000}
{"@timestamp":"2022-11-23T15:39:45.028Z","@version":"1","message":"Failed to send record topic=REDACTED {}","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.handler.IngressRequestHandlerImpl","thread_name":"vert.x-eventloop-thread-5","level":"ERROR","level_value":40000,"stack_trace":"org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for REDACTED-0:120000 ms has passed since batch creation\n","topic":"REDACTED"}
{"@timestamp":"2022-11-23T15:39:45.028Z","@version":"1","message":"Failed to produce record path=/monolith/knative-broker","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.handler.IngressRequestHandlerImpl","thread_name":"vert.x-eventloop-thread-5","level":"WARN","level_value":30000,"stack_trace":"org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for REDACTED-0:120000 ms has passed since batch creation\n","path":"/monolith/knative-broker"}
```

Broker resource:
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: knative-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: knative-kafka-broker
```

Broker configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: knative-kafka-broker
data:
  auth.secret.ref.name: knative-kafka-broker
  default.topic.partitions: "1"
  default.topic.replication.factor: "1"
```

Broker secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: knative-kafka-broker
data:
  password: REDACTED
  protocol: SASL_SSL
  sasl.mechanism: REDACTED
  user: REDACTED
```
