### ISSUE TITLE
Kafka Broker finalizer stuck if "unable to build topic config from configmap: error validating topic config from configmap invalid configuration"

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2815]
Creating a Kafka broker with an existing ConfigMap that does not have valid configuration, .e.g accidentally pointing to a MTBroker ConfigMap from a Kafka-classed Broker, leads to a Broker that cannot be deleted - the finalizer becomes stuck

to reproduce:

Config:
```yaml
apiVersion: v1
data:
  default-br-config: |
    clusterDefault:
      brokerClass: MTChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-br-default-channel
      namespace: knative-eventing
      delivery:
        retry: 10
        backoffPolicy: exponential
        backoffDelay: PT0.2S
kind: ConfigMap
```

Create a broker like:

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker
  annotations:
    eventing.knative.dev/broker.class: Kafka
```

It is stuck as:

```bash
k get brokers.eventing.knative.dev -A 
NAMESPACE   NAME     URL   AGE     READY   REASON
default     broker         3m22s   False   unable to build topic config from configmap: error validating topic config from configmap invalid configuration - numPartitions: 0 - replicationFactor: 0 - bootstrapServers: [] - ConfigMap data: map[channel-template-spec:apiVersion: messaging.knative.dev/v1...
```

Deletion of that above broker is stuck at:

```
broker.eventing.knative.dev "broker" deleted
```
