### ISSUE TITLE
Stash only relevant broker config keys on the broker status 

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2914]
**Describe the bug**

All keys from a CM are stashed as annotations. 

Given CM:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-broken-kafka-broker-config
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "1"
  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9093"
  auth.secret.ref.name: "not-present"
  blah.blup: foo-bar
```

Resulting in :

```
...
  status:
    annotations:
      auth.secret.ref.name: not-present
      blah.blup: foo-bar
      bootstrap.servers: my-cluster-kafka-bootstrap.kafka:9093
      default.topic.partitions: "10"
      default.topic.replication.factor: "1"
    conditions:
...
```

 **Expected behavior**

Not seeing the `blah.blup` annotation key on the status
