### ISSUE TITLE
Experemental filters does not work

### ISSUE THREAD

**Issue by Fyria30** [knative-sandbox/eventing-kafka-broker#2942]
**Describe the bug**
Hello! It seems to me that experemental filters work not all.

 **Expected behavior**
Seems to me it should work, but it does not
```
  filters:
    - and:
        - exact:
             type: apple
        - exact:
             type: banana
```
also cannot get ce filters worked
filters:
   - cesql: type = 'bananar'
   
Seems to me there is a type ("==" instead of "=") in ce docs  https://knative.dev/docs/eventing/experimental-features/new-trigger-filters/#conflict-with-the-current-filter-field
   
 **To Reproduce**
Switch experemental filters on
Try to make filters above

 **Knative release version**
Knative Serving 1.8.3
networking layer (kourier) 1.8.1
Serving extensions 1.8.3
Eventing 1.8.5
Apache Kafka Channel 1.8.6
Broker layer 1.8.6
Source controller 1.8.6
 **Additional context**
More info here: 
https://github.com/knative/eventing/discussions/6717

Thank you !
