### ISSUE TITLE
[Sink] Add support for SASL

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka-broker#368]
**Problem**
KafkaSink does not support SASL

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
Dumping some updates from eventing-kafka repo decisions, the plan is to extend the ConfigMap referenced by each Broker like the following:

```yaml
# ...
authSecretNamespace: <namespace>
authSecretName: <name>
```

Besides the channel format for the secret, we need certs in pkcs12 format as well. and we can use `p12` suffix for keys in that format, like:

```yaml
ca.crt: <cluster>-cluster-ca-cert.ca.crt
ca.p12: <cluster>-cluster-ca-cert.ca.p12
ca.password: <cluster>-cluster-ca-cert.ca.password
# ...
```

--- 

@slinkydeveloper, I haven't found a way to avoid calling Kubernetes API, that is easy to understand, so I'd say to start we can have a Kube client (fabric) that calls the K8s API to get the secret (no watch, only request-response), then we create Keystore and Truststore based on the secret, and finally configure Kafka clients.
