### ISSUE TITLE
Sink: SASL mechanism "PLAIN" is still not accepted

### ISSUE THREAD

**Issue by antoineco** [knative-sandbox/eventing-kafka-broker#854]
**Describe the bug**

On the latest [nightly](https://prow.knative.dev/?job=ci-knative-sandbox-eventing-kafka-broker-nightly-release) (`gcr.io/knative-nightly/knative-kafka-broker-receiver:68ce1090-a8d8-11eb-8617-9eaf6322b819`), the Kafka receiver still throws:

```
invalid SASL mechanism, expected SCRAM-SHA-256, SCRAM-SHA-512 or PLAIN got null
```

https://github.com/knative-sandbox/eventing-kafka-broker/blob/8b31f2e10866e6748aaa35de34d2fe0cbb27630e/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java#L58-L66

 **Expected behavior**

This should work after #794.

 **To Reproduce**

Secret:

```console
$  echo 'U0FTTF9TU0w=' | base64 -d
SASL_SSL
```

```console
$  echo 'UExBSU4=' | base64 -d
PLAIN
```

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kafka
data:
  password: d2hhdCBkaWQgeW91IGV4cGVjdA==
  protocol: U0FTTF9TU0w=
  sasl.mechanism: UExBSU4=
  user: aGFoYSB0cmlja2VkIHlvdQ==
```

Kafka Sink:

```yaml
apiVersion: eventing.knative.dev/v1alpha1
kind: KafkaSink
metadata:
  name: my-kafka-topic
spec:
  auth:
    secret:
      ref:
        name: kafka
  bootstrapServers:
  - <redacted>.us-east4.gcp.confluent.cloud:9092
  contentMode: structured
  topic: my-topic
```

 **Knative release version**

v0.22

 **Additional context**
