### ISSUE TITLE
`kafka-config-logging` appears 3 times in release 0.22.0

### ISSUE THREAD

**Issue by mathieux51** [knative-sandbox/eventing-kafka-broker#870]
**Describe the bug**
`https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/v0.22.0/eventing-kafka-controller.yaml` returns 3 times the `ConfigMap` `kafka-config-logging`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-logging
  namespace: knative-eventing
  labels:
    kafka.eventing.knative.dev/release: devel
data:
  config.xml: |
    <configuration>
      <appender name="jsonConsoleAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
      </appender>
      <root level="INFO">
        <appender-ref ref="jsonConsoleAppender"/>
      </root>
    </configuration>
```

 **Expected behavior**
Only one `kafka-config-logging` should be in `eventing-kafka-controller.yaml`

 **To Reproduce**
```sh
curl -L https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/v0.22.0/eventing-kafka-controller.yaml | grep -C 2 kafka-config-logging
kind: ConfigMap
metadata:
  name: kafka-config-logging
  namespace: knative-eventing
  labels:
--
--
kind: ConfigMap
metadata:
  name: kafka-config-logging
  namespace: knative-eventing
  labels:
--
--
kind: ConfigMap
metadata:
  name: kafka-config-logging
  namespace: knative-eventing
  labels:

```

 **Knative release version**
```
v0.22.0
```

 **Additional context**
I'm trying to `eventing-kafka-controller.yaml` with `kustomize build` and it's failing because of this.
