### ISSUE TITLE
Allow specifying a user-provided topic and disable topic creation

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#977]
**Problem**

- https://github.com/knative-sandbox/eventing-kafka/issues/233

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? 

Event producer and cosumer

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

Allow specifying a user-provided topic and the broker is reconciled using credentials without topic create permission.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

- This will allow lowering our required permissions to use the Broker.
- This must follow the experimental feature process

**Comment by ctron** [comment]
This would also something we would be interested in for using in @drogue-iot

**Comment by matzew** [comment]
How about using an annotation for that, on the Broker CR:

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  namespace: default
  name: my-broker
  annotations:
     kafka.eventing.knative.dev/broker.topic: my-topic
```
